### ISSUE TITLE
"2019-01-31 :	 +1 new seed of Ranbyus. " 这个新的种子是多少呢

### ISSUE THREAD

**Issue by NaviQuant** [360netlab/DGA#56]

**Comment by suqitian** [comment]
- MD5：8202ecd499a1ba153a22b74ecc1e2305
- Seed：0xb71cdaf5
- Number of domains to generate： 40
- The length of domains： 14
- [DGA](https://github.com/baderj/domain_generation_algorithms/blob/ef64b5274eb424d21c407d23d1cb8fa9b41058fa/ranbyus/may/dga.c)

**Comment by NaviQuant** [comment]
thank u very much!
